<a href="https://colab.research.google.com/github/HuanAII/Text_Generation_usingRNN/blob/main/Transformer_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [5]:
encoder_layer=nn.TransformerEncoderLayer(
    d_model=3,
    nhead=1,
    batch_first=True,
    dim_feedforward=4,
    dropout=0.1,
    bias=False
)

#Run check
example=torch.randn(1,2,3)
example
output=encoder_layer(example)
output

tensor([[[ 1.2955, -0.1566, -1.1389],
         [ 0.3669,  0.9993, -1.3663]]], grad_fn=<NativeLayerNormBackward0>)

In [ ]:
#Tu cai dat

# x = encoder_layer.self_attn(src, src, src)[0]
# x = src + x
# x1 = encoder_layer.norm1(x)
# x = encoder_layer.linear2( torch.nn.ReLU()(encoder_layer.linear1(x1)) )
# x = x + x1
# x = encoder_layer.norm2(x)
# print(x)

# *Masked Encoder*



In [6]:
import torch.nn as nn
import torch

encoder_layer=nn.TransformerEncoderLayer(d_model=3,
                                         nhead=1,
                                         batch_first=True,
                                         dim_feedforward=4,
                                         dropout=0.1,
                                         bias=False
                                         )
mask=torch.triu(torch.ones(3,3), diagonal=1).bool()#giu lai tam giac tren chuyen sang diagonal=1 thanh True
mask

tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])

In [7]:
src = torch.Tensor([[[ 0.69,  0.72, -1.41],
                     [ 0.21,  1.10, -1.31],
                     [-0.88,  0.60, -0.31]]])
out = encoder_layer(src, src_mask=mask)
print(out)

tensor([[[ 1.3610, -0.3478, -1.0132],
         [ 1.0445,  0.3035, -1.3479],
         [-0.8709,  1.4004, -0.5295]]], grad_fn=<NativeLayerNormBackward0>)


# ***Transformer***

In [8]:
import torch.nn as nn
import torch


In [10]:
encoder_layer=nn.TransformerEncoderLayer(d_model=3,
                                         nhead=1,
                                         batch_first=True,
                                         dim_feedforward=4,
                                         dropout=0.1,
                                         bias=False
                                         )

src = torch.Tensor([[[0.48, 0.44, 0.71],
                     [0.65, 0.80, 0.79]]])
context = encoder_layer(src)
print(context)
#shape input == output

tensor([[[ 1.1828, -1.2628,  0.0800],
         [ 1.2194,  0.0106, -1.2300]]], grad_fn=<NativeLayerNormBackward0>)


In [15]:
decoder_layer = nn.TransformerDecoderLayer(d_model=3,
                                           nhead=1,
                                           batch_first=True,
                                           dim_feedforward=4,
                                           dropout=0.0,
                                           bias=False)

target = torch.Tensor( [[[0.3516, 0.9509, 0.2771],
                         [0.1993, 0.0177, 0.2628],
                         [0.0774, 0.5253, 0.6413],
                         [0.6749, 0.5501, 0.1641]]])
print(target.shape)

out=decoder_layer(target, context)#tham chiếu đến encoder để sinh ra từ tiếp theo
print(out)

torch.Size([1, 4, 3])
tensor([[[-0.5717,  1.4060, -0.8344],
         [ 0.6040, -1.4094,  0.8054],
         [-0.8176, -0.5905,  1.4081],
         [ 1.4043, -0.8467, -0.5576]]], grad_fn=<NativeLayerNormBackward0>)


# MaskTransformer

In [16]:
# Encoder
encoder_layer = nn.TransformerEncoderLayer(d_model=3,
                                           nhead=1,
                                           batch_first=True,
                                           dim_feedforward=4,
                                           dropout=0.0,
                                           bias=False)

decoder_layer = nn.TransformerDecoderLayer(d_model=3,
                                           nhead=1,
                                           batch_first=True,
                                           dim_feedforward=4,
                                           dropout=0.0,
                                           bias=False)

tgt = torch.Tensor([[[0.3516, 0.9509, 0.2771],
                     [0.1993, 0.0177, 0.2628],
                     [0.0774, 0.5253, 0.6413],
                     [0.6749, 0.5501, 0.1641]]])

context = encoder_layer(src)
mask = torch.triu(torch.ones(4, 4), diagonal=1).bool()
out = decoder_layer(tgt, context, tgt_mask=mask)
print(out)

tensor([[[-1.0517,  1.3447, -0.2930],
         [-1.0491, -0.2968,  1.3459],
         [-1.4123,  0.6429,  0.7694],
         [ 0.5907,  0.8174, -1.4081]]], grad_fn=<NativeLayerNormBackward0>)
